ServerName localhost

# 1. Redirection pour l'API
# Tout ce qui commence par /api ira vers le conteneur du backend
ProxyPass "/api" "http://simple-api:8080/"
ProxyPassReverse "/api" "http://simple-api:8080/"

# 2. Redirection pour le Front-end
# Tout le reste (la racine /) ira vers le conteneur du frontend
ProxyPass "/" "http://frontend:80/"
ProxyPassReverse "/" "http://frontend:80/"