---
- name: Run App
  docker_container:
    name: "simple-api"
    image: "jsjllegoat/tp-devops-simple-api:latest"
    networks:
      - name: "app-network"
    env:
      # Voici les noms exacts que ton code Java attend (vu dans tes logs)
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "db"
      DATABASE_USER: "usr"
      DATABASE_PASSWORD: "pwd"
    recreate: yes