all:
  vars:
    ansible_user: admin
    # On lui dit de regarder le fichier qu'on vient de créer avec le 'echo'
    ansible_ssh_private_key_file: "./id_rsa" 
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    prod:
      hosts:
        jacky.shang.takima.school: