name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Delivery"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: pip install ansible

      - name: Deploy with Ansible
        # C'EST CETTE LIGNE QUI MANQUE :
        working-directory: ansible 
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa
          # On lance le playbook (on est déjà dans le dossier ansible grâce au working-directory)
          ansible-playbook -i setup.yml playbook.yml --private-key id_rsa
          rm id_rsa