name: CI CD devops 2026
on:
  push:
    branches: 
      - main
      - develop
    tags:
      - 'v*'
  pull_request:

jobs:
  # ---------------------------------------------------------
  # PARTIE 1 : CI - TEST ET QUALITÉ (S'exécute toujours)
  # ---------------------------------------------------------
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn clean verify --file simple-api/pom.xml

  sonar-analysis:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: SonarCloud Scan
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=JSJL29_tp-devops-correction-docker \
            -Dsonar.organization=jsjl29 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file simple-api/pom.xml

  # ---------------------------------------------------------
  # PARTIE 2 : CD - PUBLICATION DOCKER (Seulement sur main ou tags)
  # ---------------------------------------------------------
  
  # JOB BACKEND
  build-and-push-backend:
    needs: sonar-analysis
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.ref_name }}

  # JOB DATABASE
  build-and-push-database:
    needs: sonar-analysis
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Database
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.ref_name }}

  # JOB HTTP SERVER
  build-and-push-httpd:
    needs: sonar-analysis
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push HTTPD
        uses: docker/build-push-action@v6
        with:
          context: ./http-server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.ref_name }}